# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c806ekewT7P-KY-7BUq95aY_al0si24x
"""

import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("IPL_Cleaned.csv")

print("Dataset Loaded Successfully")
print(df.shape)
df.head()

df = pd.read_csv("IPL_Cleaned.csv")

print(df.columns)
print(df.head())

matches_per_season = (
    df[['Match_ID', 'Season']]
    .drop_duplicates()
    .groupby('Season')['Match_ID']
    .count()
)

print(matches_per_season)

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
matches_per_season.plot(kind='bar')
plt.title("Matches Played by Season")
plt.xlabel("Season")
plt.ylabel("Matches")
plt.show()

# Required Variables for Visualizations

matches_per_season = df.groupby('Season')['Match_ID'].nunique()

team_wins = (
    df[['Match_ID','Winner']]
    .drop_duplicates()['Winner']
    .value_counts()
)

top10_batsmen = (
    df.groupby('Batsman')['Runs_Scored']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top10_bowlers = (
    df.groupby('Bowler')['Wickets']
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

season_runs = (
    df.groupby('Season')['Total_Runs']
    .sum()
)

season_wickets = (
    df.groupby('Season')['Wickets']
    .sum()
)

matches_unique = df[
    ['Match_ID','Toss_Winner','Winner']
].drop_duplicates()

matches_unique['Won_After_Winning_Toss'] = (
    matches_unique['Toss_Winner']
    == matches_unique['Winner']
)

# --------------------------------------------------
# 2. Matches Won by Team — Bar Chart
# --------------------------------------------------

plt.figure(figsize=(10,5))
team_wins.plot(kind='bar', color='orange')
plt.title('Matches Won by Team')
plt.xlabel('Team')
plt.ylabel('Wins')
plt.xticks(rotation=45)
plt.show()

# --------------------------------------------------
# 3. Top 10 Run Scorers — Horizontal Bar Chart
# --------------------------------------------------

plt.figure(figsize=(10,6))
top10_batsmen.sort_values().plot(
    kind='barh',
    color='green'
)
plt.title('Top 10 Run Scorers')
plt.xlabel('Runs')
plt.ylabel('Batsman')
plt.show()

# --------------------------------------------------
# 4. Top 10 Wicket Takers — Horizontal Bar Chart
# --------------------------------------------------

plt.figure(figsize=(10,6))
top10_bowlers.sort_values().plot(
    kind='barh',
    color='red'
)
plt.title('Top 10 Wicket Takers')
plt.xlabel('Wickets')
plt.ylabel('Bowler')
plt.show()

# --------------------------------------------------
# 5. Player of the Match Awards — Bar Chart
# --------------------------------------------------

pom_count = df[
    ['Match_ID','Player_of_Match']
].drop_duplicates()

top_pom = pom_count[
    'Player_of_Match'
].value_counts().head(10)

plt.figure(figsize=(10,5))
top_pom.plot(kind='bar', color='purple')
plt.title('Top Player of Match Awards')
plt.xlabel('Player')
plt.ylabel('Awards')
plt.xticks(rotation=45)
plt.show()

# --------------------------------------------------
# 6. Toss Decision Distribution — Pie Chart
# --------------------------------------------------

toss_decision = df[
    ['Match_ID','Toss_Decision']
].drop_duplicates()

toss_decision['Toss_Decision'].value_counts().plot(
    kind='pie',
    autopct='%1.1f%%'
)

plt.title('Toss Decision Distribution')
plt.ylabel('')
plt.show()

# --------------------------------------------------
# 7. Matches Won After Winning Toss — Bar Chart
# --------------------------------------------------

plt.figure(figsize=(6,4))
sns.countplot(
    x='Won_After_Winning_Toss',
    data=matches_unique
)

plt.title('Matches Won After Winning Toss')
plt.xlabel('Won After Winning Toss')
plt.ylabel('Count')
plt.show()

# --------------------------------------------------
# 8. Season-wise Total Runs — Line Chart
# --------------------------------------------------

plt.figure(figsize=(8,5))
season_runs.plot(
    marker='o',
    linewidth=2
)

plt.title('Season-wise Total Runs')
plt.xlabel('Season')
plt.ylabel('Runs')
plt.grid(True)
plt.show()

# --------------------------------------------------
# 9. Season-wise Total Wickets — Line Chart
# --------------------------------------------------

plt.figure(figsize=(8,5))
season_wickets.plot(
    marker='o',
    linewidth=2,
    color='red'
)

plt.title('Season-wise Total Wickets')
plt.xlabel('Season')
plt.ylabel('Wickets')
plt.grid(True)
plt.show()

# --------------------------------------------------
# 10. Runs Distribution — Histogram
# --------------------------------------------------

plt.figure(figsize=(8,5))
sns.histplot(
    df['Total_Runs'],
    bins=20,
    kde=True
)

plt.title('Runs Distribution')
plt.xlabel('Runs')
plt.ylabel('Frequency')
plt.show()

# --------------------------------------------------
# 11. Team Performance Comparison — Bar Chart
# --------------------------------------------------

top_teams = team_wins.head(10)

plt.figure(figsize=(10,5))
top_teams.plot(kind='bar', color='teal')

plt.title('Team Performance Comparison')
plt.xlabel('Team')
plt.ylabel('Wins')
plt.xticks(rotation=45)
plt.show()

# --------------------------------------------------
# 12. Venue-wise Match Count — Bar Chart
# --------------------------------------------------

venue_matches = df[
    ['Match_ID','Venue']
].drop_duplicates()

top_venues = venue_matches[
    'Venue'
].value_counts()

plt.figure(figsize=(10,5))
top_venues.plot(kind='bar', color='brown')

plt.title('Venue-wise Match Count')
plt.xlabel('Venue')
plt.ylabel('Matches')
plt.xticks(rotation=45)
plt.show()

# --------------------------------------------------
# 13. Runs vs Wickets — Scatter Plot
# --------------------------------------------------

plt.figure(figsize=(8,5))
sns.scatterplot(
    x='Total_Runs',
    y='Wickets',
    data=df
)

plt.title('Runs vs Wickets')
plt.xlabel('Runs')
plt.ylabel('Wickets')
plt.show()

# --------------------------------------------------
# 14. Correlation Heatmap
# --------------------------------------------------

numeric_df = df.select_dtypes(
    include=['int64','float64']
)

plt.figure(figsize=(10,6))
sns.heatmap(
    numeric_df.corr(),
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)

plt.title('Correlation Heatmap')
plt.show()

print("All 14 Visualizations Generated Successfully")